spring:
  application:
    name: user-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    management:
      endpoints:
        web:
          exposure:
            include: hystrix.stream
