spring:
  application:
    name: zuul-service
server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    auth-service:
        strip-prefix: false
        sensitive-headers: Cookie,Set-Cookie
        path: /auth/**
        service-id: security-service
    gallery-service:
        path: /info/**
        service-id: info-service
    user-service:
          path: /users/**
          service-id: user-service