
spring:
  application:
    name: info-service
##  data:
##    mongodb:
##      uri: mongodb://localhost:27017/
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
cloud:
   config:
    discovery:
     enabled: true
      service-id: config-server